name: Tar modules

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  updater:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Update Modules
        run: ./pocopico_importer.sh

      - name: Tar modules
        run: |
          for D in `ls -d *-*`; do
            (cd ${D} && tar caf ../${D}.tgz *.ko)
          done
          (cd firmware && tar caf ../firmware.tgz *)

      # Publish a release if is a tag
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            *.tgz
